#spring.application.name=employee-service
#
## Azure SQL Configuration
#spring.datasource.url=jdbc:sqlserver://<YOUR_SERVER_NAME>.database.windows.net:1433;database=<YOUR_DATABASE_NAME>;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
#spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
#spring.datasource.username=<YOUR_USERNAME>
#spring.datasource.password=<YOUR_PASSWORD>
#
## JPA/Hibernate Configuration
#spring.jpa.database-platform=org.hibernate.dialect.SQLServer2019Dialect
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=false
#spring.jpa.properties.hibernate.format_sql=true
